# Generated by Django 6.0.5 on 2026-05-25 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название страны')),
                ('currency', models.CharField(max_length=100, verbose_name='Код валюты')),
                ('vat_rate', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Налог (%)')),
                ('language', models.CharField(max_length=100, verbose_name='Язык')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала поездки')),
                ('end_date', models.DateField(verbose_name='Дата окончания поездки')),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country', to='guides.country', verbose_name='Страна')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Поездка',
                'verbose_name_plural': 'Поездки',
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Бюджет')),
                ('daily_limit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Лимит на день')),
                ('threshold_limit', models.BooleanField(default=False, verbose_name='Наличие пороговых уведомлений')),
                ('spent', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Расход')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='guides.trip', verbose_name='Поездка')),
            ],
            options={
                'verbose_name': 'Бюджет',
                'verbose_name_plural': 'Бюджеты',
            },
        ),
    ]
