# Generated by Django 6.0.5 on 2026-05-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название страны')),
                ('currency', models.CharField(max_length=100, verbose_name='Название ваоюты')),
                ('vat_rate', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Налог (%)')),
                ('language', models.CharField(max_length=100, verbose_name='Язык')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
    ]
