# Generated by Django 6.0.5 on 2026-06-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='vat_rate',
            field=models.FloatField(default=0.0, verbose_name='Налог (%)'),
        ),
    ]
