# Generated by Django 6.0.5 on 2026-05-20 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0001_initial'),
    ]

    operations = [
    ]
