# Generated by Django 6.0.5 on 2026-05-20 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0002_auto_20260520_1210'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала поездки')),
                ('end_date', models.DateField(verbose_name='Дата окончания поездки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('сountry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='сountry', to='guides.country', verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Поездка',
                'verbose_name_plural': 'Поездки',
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Бюджет')),
                ('daily_limit', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Лимит на день')),
                ('threshold_limit', models.BooleanField(verbose_name='Наличие пороговых уведомлений')),
                ('spent', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Расход')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip', to='guides.trip', verbose_name='Поездка')),
            ],
            options={
                'verbose_name': 'Бюджет',
                'verbose_name_plural': 'Бюджеты',
            },
        ),
    ]
