# Generated by Django 6.0.5 on 2026-05-22 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0002_auto_20260520_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('link', models.URLField(verbose_name='Ссылка на статью')),
                ('update', models.DateField(auto_now=True, verbose_name='Дата обновления')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='guides.country')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
