# Generated by Django 6.0.5 on 2026-05-22 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0003_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название приложения')),
                ('description', models.TextField(verbose_name='Описание')),
                ('logo', models.URLField(blank=True, null=True, verbose_name='Ссылка на логотип')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='guides.country')),
            ],
            options={
                'verbose_name': 'Приложение',
                'verbose_name_plural': 'Приложения',
            },
        ),
    ]
