# Generated by Django 6.0.5 on 2026-05-22 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0004_localapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localapp',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='apps_logos/', verbose_name='Логотип'),
        ),
    ]
