# Generated by Django 6.0.5 on 2026-05-24 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0004_trip_is_active_alter_country_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Бюджет'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='daily_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Лимит на день'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='spent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Расход'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='threshold_limit',
            field=models.BooleanField(default=False, verbose_name='Наличие пороговых уведомлений'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='guides.trip', verbose_name='Поездка'),
        ),
    ]
