# Generated by Django 6.0.5 on 2026-05-25 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0005_alter_budget_amount_alter_budget_daily_limit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='сountry',
        ),
        migrations.AddField(
            model_name='trip',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='country', to='guides.country', verbose_name='Страна'),
            preserve_default=False,
        ),
    ]
