# Generated by Django 6.0.5 on 2026-05-22 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0005_alter_localapp_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhraseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название категории')),
                ('update', models.DateField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Категория фраз',
                'verbose_name_plural': 'Категории фраз',
            },
        ),
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.CharField(max_length=255, verbose_name='Оригинал')),
                ('translated_text', models.CharField(max_length=255, verbose_name='Перевод')),
                ('transliteration', models.CharField(blank=True, max_length=255, verbose_name='Транслитерация')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guides.country', verbose_name='Страна')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='guides.phrasecategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Фраза',
                'verbose_name_plural': 'Фразы',
            },
        ),
    ]
