# Generated by Django 6.0.5 on 2026-05-25 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0003_trip_budget'),
        ('guides', '0006_phrasecategory_phrase'),
    ]

    operations = [
    ]
